apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
   - port: 80
     targetPort: 5000
     nodePort: 31000
  selector:
    app: test-app
